# Generated by Django 2.2.4 on 2022-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runapiresultinfo',
            name='type',
            field=models.CharField(choices=[('1', '单个'), ('2', '批量'), ('3', '初始化全局参数')], default='1', max_length=10, verbose_name='类型'),
        ),
    ]
