# Generated by Django 2.0 on 2020-01-04 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_serviceinfo_status'),
        ('api', '0003_auto_20200104_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(default='', max_length=20, verbose_name='环境名称')),
                ('base_url', models.CharField(max_length=50, verbose_name='base_url')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='环境描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API环境',
                'verbose_name_plural': 'API环境',
            },
        ),
        migrations.RemoveField(
            model_name='runenv',
            name='belong_project',
        ),
        migrations.DeleteModel(
            name='RunEnv',
        ),
    ]
