# Generated by Django 2.0 on 2020-01-07 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_serviceinfo_status'),
        ('api', '0005_auto_20200105_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='', max_length=50, verbose_name='api接口用例名称')),
                ('belong_project_id', models.CharField(max_length=50, verbose_name='关联项目ID')),
                ('belong_env_id', models.CharField(max_length=50, verbose_name='关联环境ID')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('type', models.CharField(choices=[('0', '公共'), ('1', 'CI'), ('2', '非CI')], default='1', max_length=10, verbose_name='用例列表')),
                ('pre_operation', models.CharField(default='', max_length=50, verbose_name='前置操作')),
                ('api_request', models.TextField(verbose_name='请求信息')),
                ('after_operation', models.CharField(default='', max_length=50, verbose_name='后置操作')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('belong_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ServiceInfo', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': 'api用例',
                'verbose_name_plural': 'api用例',
            },
        ),
        migrations.CreateModel(
            name='GlobalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='参数名称')),
                ('belong_env', models.CharField(max_length=50, verbose_name='关联环境ID')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='参数描述')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '全局参数',
                'verbose_name_plural': '全局参数',
            },
        ),
        migrations.CreateModel(
            name='LocalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='参数名称')),
                ('belong_project_id', models.CharField(max_length=10, verbose_name='关联项目ID')),
                ('belong_env_id', models.CharField(max_length=10, verbose_name='关联环境ID')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='参数描述')),
                ('belong_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiCaseInfo', verbose_name='所属api用例')),
            ],
            options={
                'verbose_name': '局部参数',
                'verbose_name_plural': '局部参数',
            },
        ),
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='操作名称')),
                ('belong_env', models.CharField(max_length=50, verbose_name='关联环境ID')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('type', models.CharField(choices=[('0', '用例'), ('1', 'SQL'), ('2', '等待')], default='Open', max_length=10, verbose_name='操作列表')),
                ('operation', models.TextField(verbose_name='请求信息')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '前后置操作',
                'verbose_name_plural': '前后置操作',
            },
        ),
    ]
