# Generated by Django 2.0 on 2020-01-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apicaseinfo_globalparameter_localparameter_operationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationinfo',
            name='related_case_id',
            field=models.CharField(default='', max_length=20, verbose_name='关联API用例ID'),
        ),
    ]
