# Generated by Django 2.0 on 2020-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200107_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalparameterinfo',
            name='value',
            field=models.CharField(default='', max_length=100, verbose_name='参数值'),
        ),
    ]
