# Generated by Django 2.0 on 2020-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200107_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalparameterinfo',
            name='related_case',
        ),
        migrations.AddField(
            model_name='globalparameterinfo',
            name='related_case_id',
            field=models.CharField(default='', max_length=10, verbose_name='关联用例ID'),
        ),
    ]
