# Generated by Django 2.0 on 2020-01-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200107_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalparameterinfo',
            name='belong_project',
        ),
        migrations.AddField(
            model_name='globalparameterinfo',
            name='belong_project_id',
            field=models.CharField(default='', max_length=50, verbose_name='关联项目ID'),
        ),
        migrations.AlterField(
            model_name='globalparameterinfo',
            name='belong_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EnvInfo', verbose_name='关联环境ID'),
        ),
    ]
