# Generated by Django 2.0 on 2020-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200107_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalparameterinfo',
            old_name='type',
            new_name='param_type',
        ),
        migrations.AddField(
            model_name='globalparameterinfo',
            name='param_content',
            field=models.CharField(default='', max_length=100, verbose_name='参数内容'),
        ),
    ]
