# Generated by Django 2.0 on 2020-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200109_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalparameterinfo',
            name='param_content',
            field=models.CharField(default='', max_length=1024, verbose_name='参数内容'),
        ),
    ]
