# Generated by Django 2.0 on 2020-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200109_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalparameterinfo',
            name='param_type',
            field=models.CharField(choices=[('1', 'KEY-VALUE类型'), ('2', 'SQL类型'), ('3', '测试用例类型')], default='1', max_length=10, verbose_name='参数类型'),
        ),
    ]
