# Generated by Django 2.0 on 2020-01-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalparameterinfo',
            name='belong_env',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EnvInfo', verbose_name='关联环境ID'),
        ),
        migrations.AlterField(
            model_name='globalparameterinfo',
            name='related_case_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ApiCaseInfo', verbose_name='关联用例ID'),
        ),
        migrations.AlterField(
            model_name='localparameterinfo',
            name='belong_case',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.ApiCaseInfo', verbose_name='所属api用例'),
        ),
    ]
