# Generated by Django 2.0 on 2020-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200110_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicaseinfo',
            name='api_Method',
            field=models.CharField(default='', max_length=50, verbose_name='api接口Method'),
        ),
    ]
