# Generated by Django 2.0 on 2020-01-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_apicaseinfo_api_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicaseinfo',
            old_name='api_Method',
            new_name='api_method',
        ),
    ]
