# Generated by Django 2.0 on 2020-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200110_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicaseinfo',
            name='status',
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='type',
            field=models.CharField(choices=[('0', '公共'), ('1', 'CI'), ('2', '非CI'), ('3', '删除')], default='1', max_length=10, verbose_name='用例列表'),
        ),
    ]
