# Generated by Django 2.2.4 on 2020-03-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200302_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicaseinfo',
            name='belong_env_id',
        ),
        migrations.AddField(
            model_name='apicaseinfo',
            name='belong_env',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EnvInfo', verbose_name='关联环境ID'),
        ),
        migrations.AlterField(
            model_name='operationinfo',
            name='belong_env',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EnvInfo', verbose_name='关联环境ID'),
        ),
    ]
