# Generated by Django 2.2.4 on 2020-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200302_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicaseinfo',
            name='run_after_operation',
            field=models.CharField(default='', max_length=50, verbose_name='执行后操作'),
        ),
    ]
