# Generated by Django 2.2.4 on 2020-05-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200512_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicaseinfo',
            name='run_after_operation',
        ),
    ]
