# Generated by Django 2.2.4 on 2020-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_apicaseinfo_run_after_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationinfo',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='环境描述'),
        ),
    ]
