# Generated by Django 2.2.4 on 2020-07-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200702_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='runapiresultinfo',
            name='status',
            field=models.CharField(choices=[('0', '失败'), ('1', '成功')], default='1', max_length=10, verbose_name='执行状态'),
        ),
    ]
