# Generated by Django 2.2.4 on 2020-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_runapiresultinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runapiresultinfo',
            name='run_batch',
            field=models.CharField(default='', max_length=50, verbose_name='运行批次'),
        ),
    ]
