# Generated by Django 2.2.4 on 2020-07-11 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_runapiresultinfo_run_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunApiPlanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='', max_length=100, verbose_name='API执行计划名称')),
                ('run_batch', models.CharField(default='', max_length=50, verbose_name='运行批次号')),
                ('belong_project_id', models.CharField(max_length=50, verbose_name='关联项目ID')),
                ('run_user', models.CharField(default='', max_length=50, verbose_name='执行者')),
                ('status', models.CharField(choices=[('0', '失败'), ('1', '成功')], default='1', max_length=10, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='runapiresultinfo',
            name='add_time',
        ),
        migrations.AddField(
            model_name='runapiresultinfo',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='runapiresultinfo',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='runapiresultinfo',
            name='run_batch',
            field=models.CharField(default='', max_length=50, verbose_name='运行批次号'),
        ),
    ]
