# Generated by Django 2.2.4 on 2020-07-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200711_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runapiplaninfo',
            name='status',
        ),
    ]
