# Generated by Django 2.2.4 on 2020-07-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_runapiplaninfo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runapiplaninfo',
            old_name='api_name',
            new_name='name',
        ),
    ]
