# Generated by Django 2.2.4 on 2020-07-12 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200711_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicaseinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='runapiplaninfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='runapiplaninfo',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='runapiresultinfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='runapiresultinfo',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
    ]
