# Generated by Django 2.2.4 on 2020-07-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_projectinfo_status'),
        ('api', '0036_auto_20200712_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='runapiresultinfo',
            name='belong_service',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.ServiceInfo', verbose_name='所属服务'),
        ),
    ]
