# Generated by Django 2.2.4 on 2020-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200719_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runapiplaninfo',
            old_name='success_mum',
            new_name='success_num',
        ),
        migrations.AddField(
            model_name='runapiplaninfo',
            name='fail_num',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='失败数'),
        ),
    ]
