# Generated by Django 2.0 on 2019-12-31 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_departmentinfo_projectinfo_versioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='服务名称')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='服务描述')),
                ('creator', models.CharField(default='admin', max_length=10, verbose_name='创建人')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '服务信息',
                'verbose_name_plural': '服务信息',
            },
        ),
    ]
