# Generated by Django 2.0 on 2019-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='status',
            field=models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='服务状态'),
        ),
    ]
