# Generated by Django 2.2.4 on 2020-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_serviceinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioninfo',
            name='status',
            field=models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='版本状态'),
        ),
    ]
