# Generated by Django 2.2.4 on 2022-04-26 15:42

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(default='', max_length=10, verbose_name='关联需求ID')),
                ('requirement_name', models.CharField(default='', max_length=50, verbose_name='关联需求名称')),
                ('name', models.CharField(default='', max_length=50, verbose_name='执行集名称')),
                ('creator', models.CharField(default='', max_length=50, verbose_name='创建者')),
                ('executor', models.CharField(default='', max_length=50, verbose_name='执行者')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('new', '新建'), ('ongoing', '进行中'), ('finish', '完成'), ('stop', '终止')], default='new', max_length=10, verbose_name='执行集状态')),
                ('belong_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
            ],
        ),
        migrations.CreateModel(
            name='XMindCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='需求详情')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
                ('belong_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ServiceInfo', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': '思维导图用例',
                'verbose_name_plural': '思维导图用例',
            },
        ),
        migrations.CreateModel(
            name='VersionCase_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父目录')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('p_case_id', models.IntegerField(null=True, verbose_name='关联产品用例库的id')),
                ('run_batch', models.CharField(default='', max_length=50, verbose_name='导入批次号')),
                ('belong_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='VersionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父目录')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('p_case_id', models.IntegerField(null=True, verbose_name='关联产品用例库的id')),
                ('belong_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='TestCaseSuitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父目录')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='yl', max_length=5, verbose_name='类型')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('remind', models.CharField(default='', max_length=200, verbose_name='执行备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('New', '未执行'), ('Pass', '执行通过'), ('Fail', '执行失败'), ('NG', '无需执行'), ('Block', '执行阻塞')], default='New', max_length=10, verbose_name='用例执行状态')),
                ('belong_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.TestCaseSuit', verbose_name='所属执行集')),
                ('belong_version_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.VersionCase', verbose_name='关联的版本用例')),
            ],
            options={
                'verbose_name': '测试用例执行集详情',
                'verbose_name_plural': '测试用例执行集详情',
            },
        ),
        migrations.CreateModel(
            name='TestCase_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父目录')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('import_batch', models.CharField(default='', max_length=50, verbose_name='导入批次号')),
                ('belong_project', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '产品库用例临时表',
                'verbose_name_plural': '产品库用例临时表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父目录')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('belong_project', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.ProjectInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
    ]
