# Generated by Django 2.0 on 2019-12-25 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_departmentinfo_projectinfo_versioninfo'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='case.TestCase', verbose_name='父目录')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='TestCaseSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.IntegerField(default='', verbose_name='关联需求ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='执行集名称')),
                ('creator', models.CharField(default='', max_length=50, verbose_name='创建者')),
                ('executor', models.CharField(default='', max_length=50, verbose_name='执行者')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('statue', models.CharField(choices=[('new', '新建'), ('ongoing', '进行中'), ('finish', '完成'), ('stop', '终止')], default='new', max_length=10, verbose_name='执行集状态')),
                ('belong_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSuitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('parent_area', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='父目录')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='yl', max_length=5, verbose_name='类型')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('remind', models.CharField(default='', max_length=200, verbose_name='执行备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('New', '未执行'), ('Pass', '执行通过'), ('Fail', '执行失败'), ('NG', '无需执行'), ('Block', '执行阻塞')], default='New', max_length=10, verbose_name='用例执行状态')),
                ('belong_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.TestCaseSuit', verbose_name='所属执行集')),
            ],
            options={
                'verbose_name': '测试用例执行集详情',
                'verbose_name_plural': '测试用例执行集详情',
            },
        ),
        migrations.CreateModel(
            name='VersionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用例主题')),
                ('jb', models.CharField(choices=[('level0', 'level0'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], default='level1', max_length=10, verbose_name='用例级别')),
                ('precondition', models.CharField(default='', max_length=200, verbose_name='预置条件')),
                ('operation', models.CharField(default='', max_length=200, verbose_name='操作步骤')),
                ('expect_result', models.CharField(default='', max_length=200, verbose_name='期望结果')),
                ('case_desc', models.CharField(default='', max_length=200, verbose_name='用例备注')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('type', models.CharField(choices=[('ml', '目录'), ('yl', '用例')], default='', max_length=5, verbose_name='类型')),
                ('p_case_id', models.IntegerField(null=True, verbose_name='关联产品用例库的id')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('belong_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='case.VersionCase', verbose_name='父目录')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
        migrations.AddField(
            model_name='testcasesuitdetail',
            name='belong_version_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.VersionCase', verbose_name='关联的版本用例'),
        ),
    ]
