# Generated by Django 2.2.4 on 2022-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase_tmp',
            name='case_desc',
            field=models.CharField(default='', max_length=2000, verbose_name='用例备注'),
        ),
        migrations.AlterField(
            model_name='testcase_tmp',
            name='expect_result',
            field=models.CharField(default='', max_length=2000, verbose_name='期望结果'),
        ),
        migrations.AlterField(
            model_name='testcase_tmp',
            name='operation',
            field=models.CharField(default='', max_length=2000, verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='testcase_tmp',
            name='precondition',
            field=models.CharField(default='', max_length=2000, verbose_name='预置条件'),
        ),
        migrations.AlterField(
            model_name='versioncase',
            name='case_desc',
            field=models.CharField(default='', max_length=2000, verbose_name='用例备注'),
        ),
        migrations.AlterField(
            model_name='versioncase',
            name='expect_result',
            field=models.CharField(default='', max_length=2000, verbose_name='期望结果'),
        ),
        migrations.AlterField(
            model_name='versioncase',
            name='operation',
            field=models.CharField(default='', max_length=2000, verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='versioncase',
            name='precondition',
            field=models.CharField(default='', max_length=2000, verbose_name='预置条件'),
        ),
        migrations.AlterField(
            model_name='versioncase_tmp',
            name='case_desc',
            field=models.CharField(default='', max_length=2000, verbose_name='用例备注'),
        ),
        migrations.AlterField(
            model_name='versioncase_tmp',
            name='expect_result',
            field=models.CharField(default='', max_length=2000, verbose_name='期望结果'),
        ),
        migrations.AlterField(
            model_name='versioncase_tmp',
            name='operation',
            field=models.CharField(default='', max_length=2000, verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='versioncase_tmp',
            name='precondition',
            field=models.CharField(default='', max_length=2000, verbose_name='预置条件'),
        ),
    ]
