# Generated by Django 2.0 on 2019-12-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20191225_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasesuitdetail',
            old_name='parent_area',
            new_name='parent_area1',
        ),
    ]
