# Generated by Django 2.0 on 2019-12-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20191225_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasesuitdetail',
            old_name='parent_area1',
            new_name='parent_area',
        ),
    ]
