# Generated by Django 2.0 on 2019-12-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20191225_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasesuit',
            old_name='statue',
            new_name='status',
        ),
    ]
