# Generated by Django 2.0 on 2019-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20191226_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasesuit',
            name='requirement_name',
            field=models.CharField(default='', max_length=50, verbose_name='关联需求名称'),
        ),
    ]
