# Generated by Django 2.0 on 2019-12-31 15:07

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_serviceinfo_status'),
        ('case', '0008_testcasesuit_requirement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMindCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='项目名称')),
                ('designer', models.CharField(default='', max_length=50, verbose_name='设计者')),
                ('modifier', models.CharField(default='', max_length=50, verbose_name='修改者')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='需求详情')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=5, verbose_name='用例状态')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectInfo', verbose_name='所属项目')),
                ('belong_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ServiceInfo', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': '思维导图用例',
                'verbose_name_plural': '思维导图用例',
            },
        ),
    ]
