# Generated by Django 2.0 on 2020-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_xmindcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmindcase',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='用例主题'),
        ),
    ]
