# Generated by Django 2.2.4 on 2020-07-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20200104_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='testcasesuitdetail',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='level',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='testcase',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='testcasesuitdetail',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='versioncase',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父目录'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='belong_project',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.ProjectInfo', verbose_name='所属项目'),
        ),
    ]
