# Generated by Django 2.2.4 on 2020-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20200805_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='parent_list',
        ),
        migrations.RemoveField(
            model_name='versioncase',
            name='parent_list',
        ),
    ]
