# Generated by Django 2.0 on 2019-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_buginfo_bugrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buginfo',
            name='status',
            field=models.CharField(choices=[('Open', '打开'), ('ReOpen', '重新打开'), ('Fixed', '已解决'), ('Rejected', '无需解决'), ('Closed', '已关闭')], default='Open', max_length=10, verbose_name='用例状态'),
        ),
    ]
