# Generated by Django 2.2.4 on 2020-11-16 17:21

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default='', verbose_name='所属项目')),
                ('name', models.CharField(max_length=50, verbose_name='需求名称')),
                ('detail', DjangoUeditor.models.UEditorField(verbose_name='需求详情')),
                ('creator', models.CharField(default='', max_length=10, verbose_name='产品')),
                ('solver', models.CharField(default='', max_length=10, verbose_name='需求负责人')),
                ('tester', models.CharField(default='', max_length=10, verbose_name='测试对接人')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '新建'), ('2', '开发中'), ('3', '测试验收'), ('4', '验收完成'), ('5', '暂停')], default='1', max_length=10, verbose_name='需求状态')),
                ('file', models.FileField(upload_to='requirement/file/', verbose_name='附件')),
                ('belong_version', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.VersionInfo', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '需求信息表',
                'verbose_name_plural': '需求信息表',
            },
        ),
        migrations.CreateModel(
            name='RequirementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='任务名称')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='需求详情')),
                ('creator', models.CharField(default='', max_length=10, verbose_name='创建者')),
                ('owner', models.CharField(default='', max_length=10, verbose_name='任务负责人')),
                ('type', models.CharField(choices=[('fx', '需求分析'), ('sj', '需求设计'), ('bx', '用例编写'), ('ps', '用例评审'), ('kf', '开发需求'), ('tys', '测试验收'), ('cys', '产品验收'), ('qt', '其他任务')], default='', max_length=10, verbose_name='任务类型')),
                ('progress', models.CharField(choices=[('0', '0%'), ('5', '5%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('85', '85%'), ('90', '90%'), ('95', '95%'), ('100', '100%')], default='0', max_length=10, verbose_name='任务进度')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('status', models.IntegerField(choices=[('0', '删除'), ('1', '正常')], default='1', verbose_name='用例状态')),
                ('belong_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirement.RequirementInfo', verbose_name='所属需求')),
            ],
            options={
                'verbose_name': '需求任务信息',
                'verbose_name_plural': '需求任务信息',
            },
        ),
        migrations.CreateModel(
            name='TaskTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=10, verbose_name='任务所属者')),
                ('times', models.FloatField(default=0.0, max_length=10, verbose_name='任务耗费时间')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('belong_task', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='requirement.RequirementTask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务时间信息',
                'verbose_name_plural': '任务时间信息',
            },
        ),
    ]
