# Generated by Django 2.0 on 2019-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0002_requirementinfo_requirementtask_tasktimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementinfo',
            name='status',
            field=models.IntegerField(choices=[('0', '删除'), ('1', '新建'), ('2', '开发中'), ('3', '测试验收'), ('4', '验收完成'), ('5', '暂停')], default='1', verbose_name='需求状态'),
        ),
    ]
